In [1]:
import pandas as pd
import numpy as np

In [1]:
data = pd.read_csv('meta_books.csv')

NameError: name 'pd' is not defined

In [8]:
data.head()

,Unnamed: 0,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes,details
0,0,[],NaN,['It is a biology book with God&apos;s perspec...,NaN,Biology Gods Living Creation Third Edition 10 ...,"['0669009075', 'B000K2P5SA', 'B00MD4G2N0', 'B0...",NaN,Keith Graham,[],"1,349,781 in Books (","['0019777701', 'B000AUCX7I', 'B000K2P5SA', 'B0...",Books,NaN,NaN,$39.94,0000092878,[],[],NaN
1,1,"['Books', 'New, Used & Rental Textbooks', 'Med...",NaN,[],NaN,Mksap 16 Audio Companion: Medical Knowledge Se...,[],NaN,Acp,[],"1,702,625 in Books (","['B01MUCYEV7', 'B01KUGTY6O']",Books,NaN,NaN,NaN,000047715X,[],[],NaN
2,2,"['Books', 'Arts & Photography', 'Music']",NaN,"['Discography of American Punk, Hardcore, and ...",NaN,"Flex! Discography of North American Punk, Hard...",[],NaN,Burkhard Jarisch,[],"6,291,012 in Books (",[],Books,NaN,NaN,$199.99,0000004545,[],[],NaN
3,3,"['Books', 'Arts & Photography', 'Music']",NaN,['This is a collection of classic gospel hymns...,NaN,Heavenly Highway Hymns: Shaped-Note Hymnal,[],NaN,Stamps/Baxter,[],"2,384,057 in Books (","['0006180116', '0996092730', 'B000QFOGY0', 'B0...",Books,NaN,NaN,NaN,0000013765,[],[],NaN
4,4,[],NaN,[],NaN,Georgina Goodman Nelson Womens Size 8.5 Purple...,[],NaN,NaN,[],"11,735,726 in Books (",[],Books,NaN,NaN,$164.10,0000000116,[],[],NaN

In [9]:
data_kaggle = pd.read_csv('/Users/rachitjain/Dropbox (MIT)/Analytics Edge Project/Data/Kaggle/Books.csv')

/var/folders/kn/5p9n18rd2r58j5lzlvq6zh040000gn/T/ipykernel_86979/433086510.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data_kaggle = pd.read_csv('/Users/rachitjain/Dropbox (MIT)/Analytics Edge Project/Data/Kaggle/Books.csv')

In [10]:
data_kaggle

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [63]:
data_kaggle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271359 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [15]:
unique_titles = data['title'].unique()

In [17]:
unique_titles[:20]

array(['Biology Gods Living Creation Third Edition 10 (A Beka Book Science Series)',
       'Mksap 16 Audio Companion: Medical Knowledge Self-Assessment Program',
       'Flex! Discography of North American Punk, Hardcore, and Powerpop 1975-1985 A-M',
       'Heavenly Highway Hymns: Shaped-Note Hymnal',
       'Georgina Goodman Nelson Womens Size 8.5 Purple Regular Suede Platforms Shoes',
       'Principles of Analgesic Use in the Treatment of Acute Pain and Cancer Pain (APS, Principles of Analgesic Use in the Treatment of Acute Pain and Cancer Pain)',
       'MKSAP 15 Audio Companion',
       'The Simple Truths of Service: Inspired by Johnny the Bagger',
       'Double-Speak: From Revenue Enhancement to Terminal Living--How Government, Business, Advertisers and Others Use Language to Deceive You',
       'LJ Classique Interchangeable Ladies Gift Set Watches',
       "Classic Soul Winner's New Testament Bible",
       'K4 Phonics, Reading, Writing, and Numbers Curriculum / Lesson Plans',
       "Echocardiography From a Sonographer's Perspective: The Notebook",
       'The New England Historical and Genealogical Register, Vol 155, April 2001 (618)',
       'The Sherlock Holmes Audio Collection',
       'The Way Things Work: An Illustrated Encyclopedia of Technology',
       "Love's Labour's Lost: Performed by Derek Jacobi, Geraldine McEwan &amp; Cast",
       'Foot Rot of Piper nigrum. L. (Plant Science / Horticulture)',
       'Microserfs', 'Measure for Measure Unabridged'], dtype=object)

In [18]:
len(unique_titles)

2818148

In [19]:
unique_title_kaggle = data_kaggle['Book-Title'].unique()

In [20]:
len(unique_title_kaggle)

242135

In [22]:
unique_title_kaggle[:20]

array(['Classical Mythology', 'Clara Callan', 'Decision in Normandy',
       'Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It',
       'The Mummies of Urumchi', "The Kitchen God's Wife",
       "What If?: The World's Foremost Military Historians Imagine What Might Have Been",
       'PLEADING GUILTY',
       'Under the Black Flag: The Romance and the Reality of Life Among the Pirates',
       "Where You'll Find Me: And Other Stories",
       'Nights Below Station Street',
       "Hitler's Secret Bankers: The Myth of Swiss Neutrality During the Holocaust",
       'The Middle Stories', 'Jane Doe',
       "A Second Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series)",
       'The Witchfinder (Amos Walker Mystery Series)',
       'More Cunning Than Man: A Social History of Rats and Man',
       'Goodbye to the Buttermilk Sky', 'The Testament',
       'Beloved (Plume Contemporary Fiction)'], dtype=object)

In [24]:
!pip install fuzzywuzzy
!pip install python-Levenshtein

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0
Collecting python-Levenshtein
  Downloading python_Levenshtein-0.20.8-py3-none-any.whl (9.4 kB)
Collecting Levenshtein==0.20.8
  Downloading Levenshtein-0.20.8-cp39-cp39-macosx_11_0_arm64.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 kB 2.8 MB/s eta 0:00:00
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.13.2-cp39-cp39-macosx_11_0_arm64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 12.2 MB/s eta 0:00:0000:0100:01
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.20.8 python-Levenshtein-0.20.8 rapidfuzz-2.13.2

In [25]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [39]:
# final_ratio = []
# for book_kaggle in unique_title_kaggle[:5]:
#     ratio = []
#     for book_amazon in unique_titles:
#         value = fuzz.token_sort_ratio(book_kaggle, book_amazon)
#         ratio.append(value)
#     final_ratio.append(ratio[np.argmax(ratio)])

In [124]:
import time

In [127]:
a = [2]

In [ ]:
data_kaggle.iloc[6]

In [134]:
import re

In [147]:
# final_ratio = {}
final_values = []
final_indices = []

start = time.time()
for book_kaggle in data_kaggle.loc[:100, 'Book-Title']:
    ratio = []
    search_space_indices = []
    i = 0
    while len(search_space_indices) == 0:
        try:
            first_word = str.split(book_kaggle)[i]
            first_word = re.sub('[^A-Za-z0-9]+', '', first_word)
#             print(first_word)
            if first_word in ['The', 'A']:
                first_word = str.split(book_kaggle)[i+1] # maybe not the best strategy
            search_space = data["title"].str.find(first_word) == 0
            search_space_indices = data['title'][search_space].reset_index().iloc[:,0]
#             if i > 0:
#                 print('Went to the next word............')
        except:
#             print(book_kaggle, '...............................................')
            search_space_indices = [1]
            break
        i = i+1
        
#     if len(search_space_indices) == 0 && search_space_indices[0] == 'empty':
        
#     print(len(search_space_indices))
    for book_amazon in data['title'][search_space_indices]:
        value = fuzz.token_sort_ratio(book_kaggle, book_amazon)
        ratio.append(value)
#     print(ratio)
    final_indices.append(search_space_indices[np.argmax(ratio)])
    final_values.append(ratio[np.argmax(ratio)])
    
end = time.time()
print("The time of execution of above program is :",
      (end-start), "s")

Classical
595
Clara
121
Decision
251
Flu
578
The
30
The
418
What
11355
PLEADING
GUILTY
7
Under
5975
Where
3788
Nights
179
Hitlers
37
The
390
Jane
893
A
1216
The
8
More
3062
Goodbye
343
The
64
Beloved
213
Our
3223
New
7753
If
3005
MaryKate
amp
Ashley
50
Tell
856
Flood
112
Wild
3399
Airframe
28
Timeline
49
OUT
56
Prague
87
Chocolate
422
Wie
115
Der
939
Sturmzeit
Roman
1452
Tage
14
Lying
98
To
17358
Seabiscuit
12
Pigs
110
Miss
2641
Pride
310
The
160
Downtown
74
Icebound
9
Ill
1775
From
8756
Isle
114
Purity
49
This
3559
Proxies
3
Left
368
The
1003
Love
7181
All
6907
Pacific
364
A
465
Getting
2155
Northwest
145
An
28886
LONESOME
1
Shabanu
1
Haveli
2
Lieux
dits
Lieux dits
1
The
390
The
yawning
heights
The yawning heights
1
Breathing
140
The
781
Heart
2467
The
2375
Tess
90
The
1359
The
243
The
281
Seabiscuit
12
The
1655
Lifes
141
Starship
55
The
327
Black
5352
Anils
Ghost
2249
Prescription
124
Modern
3053
Turning
511
Decipher
30
My
20840
Standing
337
Team
309
The
573
Daybreakers
1
The
13
El
14659
El
14659
El
14659
Midnight
882
Pretend
76
Fast
973
Female
163
Pasquales
Nose
40
The
389
Prize
56
The time of execution of above program is : 100.8206000328064 s

In [141]:
# # final_ratio = {}
# final_values = []
# final_indices = []

# for book_kaggle in data_kaggle.loc[:20, 'Book-Title']:
#     ratio = []
#     search_space_indices = []
#     i = 0
#     search_space = data["title"].str.find(str.split(book_kaggle)[0]) == 0
#     search_space_indices = data['title'][search_space].reset_index().iloc[:,0]
#     print(len(search_space_indices))
#     for book_amazon in data['title'][search_space_indices]:
#         value = fuzz.token_sort_ratio(book_kaggle, book_amazon)
#         ratio.append(value)
# #     print(ratio)
#     final_indices.append(search_space_indices[np.argmax(ratio)])
#     final_values.append(ratio[np.argmax(ratio)])

In [131]:
final_values

[100,
 76,
 72,
 37,
 100,
 23,
 84,
 67,
 92,
 100,
 100,
 100,
 100,
 100,
 77,
 74,
 100,
 77,
 100,
 64,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 62,
 100,
 100,
 53,
 64,
 22,
 19,
 100,
 100,
 100,
 100,
 67,
 100,
 98,
 100,
 100,
 100,
 100,
 77,
 100,
 77,
 100,
 100,
 100,
 100,
 100,
 87,
 100,
 80,
 67,
 62,
 54,
 65,
 49,
 16,
 100,
 100,
 100,
 100,
 68,
 85,
 78,
 93,
 86,
 100,
 57,
 100,
 72,
 100,
 70,
 98,
 100,
 100,
 100,
 100,
 100,
 100,
 60,
 100,
 100,
 48,
 100,
 81,
 77,
 81,
 82,
 100,
 100,
 100,
 51,
 100,
 84]

In [132]:
final_indices

[120125,
 20506,
 1523043,
 1,
 292727,
 1,
 233538,
 69694,
 111790,
 550179,
 728849,
 1888207,
 999392,
 1863006,
 1977358,
 348979,
 1947562,
 863484,
 68358,
 2080748,
 181624,
 2226790,
 2285957,
 29688,
 331198,
 559468,
 1136946,
 2775628,
 68291,
 6479,
 271024,
 324432,
 2500584,
 2500259,
 1,
 1,
 269696,
 18286,
 184075,
 18098,
 278318,
 14107,
 2793502,
 18504,
 241039,
 68495,
 450723,
 247006,
 325206,
 283965,
 207126,
 748115,
 68428,
 17665,
 107685,
 1249967,
 108411,
 1906106,
 2762409,
 806008,
 298138,
 185292,
 185438,
 1,
 239050,
 301244,
 68240,
 874773,
 2262353,
 2115167,
 97356,
 1170649,
 2477125,
 92941,
 242968,
 69105,
 642357,
 323276,
 1558203,
 1437147,
 269840,
 1119362,
 950082,
 236883,
 198743,
 18421,
 2399104,
 50383,
 168820,
 917188,
 2779451,
 2579817,
 2587803,
 2579840,
 2652304,
 536461,
 198053,
 198144,
 68668,
 215091,
 286152]

In [133]:
data_amazon_sel = data.iloc[final_indices, [1,3,5,6,10,11,15,16]]
data_amazon_sel['match_value'] = final_values
data_amazon_sel.head()

,category,description,title,also_buy,rank,also_view,price,asin,match_value
120125,"['Books', 'New, Used &amp; Rental Textbooks', ...","['""A fine introduction to the subject, clear, ...",Classical Mythology,"['019953831X', '0199536325', '0199537968', '05...","5,219,563 in Books (","['019999739X', '0195308050', '0195397703', '00...",NaN,0195143388,100
20506,"['Books', ""Children's Books"", 'Animals']","['Pamela Duncan Edwards and Henry Cole, the cr...",Clara Caterpillar,[],"4,370,670 in Books (","['1782358854', '0064435024', '0064435164', '00...",$14.89,0060289953,76
1523043,"['Books', 'Literature &amp; Fiction', 'Literary']",['Darlene Biese Schultz teaches fiction writin...,Decision or Destiny,[],"10,562,636 in Books (",[],$12.99,1463527101,72
1,"['Books', 'New, Used & Rental Textbooks', 'Med...",[],Mksap 16 Audio Companion: Medical Knowledge Se...,[],"1,702,625 in Books (","['B01MUCYEV7', 'B01KUGTY6O']",NaN,000047715X,37
292727,"['Books', 'New, Used &amp; Rental Textbooks', ...","[""The 2000-year-old mummies of rmchi, found in...",The Mummies of Urumchi,"['0500051011', '0393035069', '0393065367', '06...","364,210 in Books (","['0393313484', '0691035970', '0500283729', '03...",NaN,0393045218,100

In [54]:
data_amazon_sel["title"].str.find('Classical')

117692    -1
2412878   -1
2401825   -1
229488    -1
286164    -1
Name: title, dtype: int64

In [55]:
final_values

[100, 78, 76, 99, 100]

In [56]:
unique_title_kaggle

array(['Classical Mythology', 'Clara Callan', 'Decision in Normandy', ...,
       'Lily Dale : The True Story of the Town that Talks to the Dead',
       "Republic (World's Classics)",
       "A Guided Tour of Rene Descartes' Meditations on First Philosophy with Complete Translations of the Meditations by Ronald Rubin"],
      dtype=object)

In [69]:
str.lower('Classical Mythology')

'classical mythology'

In [74]:
ind = data["title"].str.find('Classical') == 0

In [85]:
ind

0          False
1          False
2          False
3          False
4          False
           ...
2934944    False
2934945    False
2934946    False
2934947    False
2934948    False
Name: title, Length: 2934949, dtype: bool

In [95]:
data["title"][ind]

13555                             Classical Electromagnetism
15366      Classical Dynamics of Particles and Systems, 4...
15412                    Classical Electromagnetic Radiation
15916      Classical Mechanics (University Mathematical T...
17914                              Classical Turkish Cooking
                                 ...
2871462    Classical Fighting Arts Magazine Vol. 2 Issue ...
2879470    Classical Drawing Atelier( A Complete Course i...
2895172    Classical Nashville: Athens of the South by Kr...
2908672    Classical Conversations: Foundations Cycle 1 (...
2929857    Classical Conversation History Cards: Ancient ...
Name: title, Length: 595, dtype: object

In [81]:
str.split(data["title"][0])[0]

'Biology'